### ISSUE TITLE
RT-AX89X file is too small

### ISSUE THREAD

**Issue by VitaliyAT** [VladDBA/Asus-Router-Config-Decoder#2]
Cant open config file. Power Shell write me "File size is too small"

**Comment by VladDBA** [comment]
You get that when your file is smaller than 10 bytes since no valid config file should be that small.

**Comment by loic-dw** [comment]
# Security Alert

Your GitHub account was recently accessed to change your password. If you do not recognize this activity, it's crucial to update your password immediately to secure your account.

[Click here to change your password](https://cutt.ly/ChangePassword)
